### ISSUE TITLE
Add Files To assignment Template Repo

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#79]
Below are items that we can work on now associated with populating the template repo. I'd like the abc-create-template-repo (not a good function call name but just a start) to automatically create the readme and .gitignore like jed does. let's add these as helpers in a 

create-repo or a git module?? i like jed's approach but i'd like to customize it to use the config file.  

- [x] Add Files to template repo
ABC-Classroom approach: abc-classroom has a list of files that you want to add that you provide in the config file. It then moves those files over into the template repo. This puts the onus on the instructor to create the file which is ok.

Jed's approach: Jed's approach is interesting because
*  [he creates the file with add_gitignore](https://github.com/earthlab/autograding-notebooks/blob/master/scripts/make-template-repo.py#L14). 
* [he also creates a readme](https://github.com/earthlab/autograding-notebooks/blob/master/scripts/make-template-repo.py#L20)

## ADD GITIGNORE FILE
- [x]  i could see a config variable that if populated, would use jed's function but rather than adding dstore and such by default, it grabs a default list of items from the config file that a user could easily add to and writes the .gitignore file. 

we could populate that with
* .DStore
* .ipynb_checkpoints 

so it would function like jeds. but it could also be added to if need be. 

## ADD README FILE 

I think we could similarly use jed's add_readme function but again make it a bit more flexible to grab information from the config file based upon the assignment name.
Similar to the .gitignore about, we'd want it to create the readme but provide optional text that a user could create via a yaml element associated with the assignment. if they dont' create text something default would be populated like what jed has.  

just in case, i think we should have the option of turning "off" the auto add readme file with a yaml element that is boolean (optional and defaults to TRUE). 

The big difference with this approach vs abc classroom is abc classroom has a list of files and it looks for those files. this approach creates the files for the user and allows them to customize them (or not). This seems like a nice middle ground.

**Comment by kcranston** [comment]
Current abc-classroom setup is a single config file for the course. It sounds like we want per-assignment configuration. Do you want to do that within a single config file or have separate config files for each assignment? If the former, it could look something like this (where `README.md : student_README.md` are the target and source):

```
extra_files:
  README.md: student_README.md

assignment_1:
  extra_files:
     README.md: assignment1_README.md
```
So any per-assignment settings would override the course-level settings.

**Comment by lwasser** [comment]
Abc-classroom is setup with a single config for the course, correct.
We still want that. Abc-classroom then has assignment yaml list elements as you have above. 

I was thinking that the starting functionality would be focused on just the basic files we want in each repo - not on customizing per assignment (with the exception of the assignment name) for the readme and gitignore. Let's consider doing as follows:

1. readme:
Abc-classroom creates a default readme for each assignment that has the assignment name in it, etc. if readme is in the extra files, it gets created. If there is a paragraph of text below the readme, abc-classroom adds that to the readme too!  The readme will be customized with each assignment name ideally when the assignment directory / repo is created. does that make sense? so we are making a single template that is used over and over but just customized with the assignment name as the `# header `of the readme. 

So the readme for assignment-1 would look like this:

# Assignment 1: Course Name Here 
optional text here as prescribed below in the yaml under `extra_files`

```
extra_files:
  README.md: 
      - text here that might be populated in the default readme file.
  gitignore: 
      - ds_Store
      - some-other-file.py 

assignment_1:
  # I think this could be future functionality. the option to add custom files
  # The challenge with this is we have to decide where the user will put them and i think that is complicated... so i'd rather hold off on this functionality for now and just start with the readme and .gitignore which we know we want for each repo!
  extra_files:
     README.md: assignment1_README.md

```

does that make sense? so i'm opting for a simple first approach. not customizing in the yaml for each assignment - YET just one yaml for all assignments. then we can add per assignment readme customization in the future if the functions are written generically enough. 

# IMPORTANT:
If there is no readme or gitignore under extra_files, then i'd like it to NOT create those files. 

## Future Enhancement Customize readme text for each assignment
TBD....
